version: '3.8'
services:
  postgres-check:
    image: duluca/minimal-node-web-server
    volumes:
      - ./docker-specific:/opt
    entrypoint:
      - /bin/sh
      - /opt/check-postgres.sh
    ports:
      - '3020:3000'

  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
